<?php
/**
 * Generated from the Bin Shihon content DOCX.
 * Source document instructions are treated as content data only.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'home' => array(
		'slug' => 'home',
		'number' => '01',
		'ar' => array(
			'title' => 'الصفحة الرئيسية',
			'blocks' => array(
				'شريط التنقل',
				'الرئيسية   ·   الشركة   ·   الإطارات   ·   اختر إطارك   ·   الوكالات   ·   الاعتمادات   ·   تواصل معنا',
				'اطلب عرض سعر',
				'الواجهة الرئيسية',
				'موثوق في كل ميل',
				'إطاراتك تصل قبل أن تحتاجها، وبسعر المستورد مباشرة',
				'نستورد الإطارات من مصانع معتمدة في الصين وكوريا الجنوبية وتايلند، ونخزّنها في الرياض وجدة. فحين تطلب، البضاعة موجودة على الأرض ولا تنتظر شحنة في البحر، والسعر يصلك من المصدر دون وسيط بينكما.',
				'اطلب عرض سعر خلال يوم عمل',
				'تصفّح الإطارات',
				'شريط الثقة',
				'جهة معتمدة، لا مجرد مورّد',
				'▪  مشغل اقتصادي معتمد (أولوية) من هيئة الزكاة والضريبة والجمارك، سبتمبر 2025',
				'▪  في السوق السعودي منذ 2016',
				'▪  إحدى عشرة وكالة عالمية تحت سقف واحد',
				'▪  مستودعان رئيسيان في الرياض وجدة',
				'نمثّل في المملكة: Nexen · Trazano · Boto · Joyall · Onyx · Landspider · Cachland · Anniet · Fiermax · Kaytoon · ZC',
				'أداة اختيار الإطار',
				'ما هو الإطار المناسب لسيارتك؟',
				'جاوب على أسئلة سريعة، ونرجع لك بالمقاس وبترشيح مبني على استخدامك الفعلي لا على السعر وحده. أقل من دقيقة، وبدون تسجيل.',
				'ابدأ الآن',
				'المزايا الأساسية',
				'استيراد مباشر',
				'نشتري من المصنع لا من وسيط، فالسعر الذي يصلك مرّ بأقل عدد ممكن من الأيدي، وأي ملاحظة على الجودة نرجع بها إلى المصنع مباشرة.',
				'مخزون على الأرض',
				'المستودعات مليئة قبل أن تطلب. مقاسك موجود اليوم، ولست مضطراً لانتظار حاوية قادمة.',
				'مقاسات تغطي السوق',
				'من سيارة العائلة إلى شاحنة النقل الثقيل. المقاسات الشائعة متوفرة دائماً، والنادرة نوفّرها بطلب مسبق.',
				'الحل',
				'اختر حسب استخدامك، لا حسب السعر وحده.',
				'إطارات الركاب',
				'للسيدان والهاتشباك والاستخدام اليومي داخل المدن وعلى الخطوط السريعة. ثبات على السرعة، فرملة تعتمد عليها، وهدوء داخل السيارة.',
				'الدفع الرباعي والطرق المختلطة',
				'أسفلت وطريق ترابي في الرحلة نفسها. جدار جانبي مقوّى، ونقشة تمسك الرمل والحصى دون أن تفقد هدوءها على الطريق المعبّد.',
				'الشاحنات والحافلات',
				'حمولة عالية ومسافات طويلة بين المدن. نقشات مخصصة للمحور الأمامي والمحور القائد والمقطورة.',
				'مجموعة Velocità',
				'مصممة لكل طريق تسلكه. نقشة تصرّف الماء، خلطة تتحمّل الحرارة، وعمر تشغيلي محسوب.',
				'شوف المقاسات',
				'الأرقام',
				'▪  2016 — سنة التأسيس',
				'▪  11 — وكالة عالمية',
				'▪  3 — أسواق استيراد',
				'▪  2 — مستودع رئيسي',
				'الفوائد',
				'تكلفة أقل لكل كيلومتر',
				'الرقم المهم ليس سعر الإطار، بل كم كيلومتراً مشى قبل التبديل. نساعدك على الاختيار بهذا المنطق.',
				'توريد لا يتأخر',
				'الاعتماد الجمركي يعني فسحاً أسرع، والمخزون المحلي يعني أن طلبك لا ينتظر شحنة.',
				'اختيار صحيح من أول مرة',
				'أرسل المقاس أو موديل السيارة، ويرجع لك فريقنا بترشيح مبني على استخدامك الفعلي.',
				'سعر تعرف من أين جاء',
				'نحن المستورد. لا طبقة تضيف على السعر ثم تشرح لك سبب الزيادة.',
				'كيف نشتغل',
				'▪  أرسل لنا المقاسات والكميات، أو موديل سيارتك.',
				'▪  يرجع لك عرض سعر واضح ومدة تسليم محددة.',
				'▪  نجهّز الشحنة من مستودع الرياض أو جدة.',
				'▪  تستلم في موقعك، وتبقى على تواصل مع الشخص نفسه.',
				'ابدأ الآن',
				'شبكتنا ووكالاتنا',
				'إحدى عشرة علامة عالمية تعمل معنا، ومستودعان في الرياض وجدة، وشبكة توزيع تصل إلى مناطق المملكة. هذا يعني أن الطلب الواحد يغطي أكثر من علامة وأكثر من فئة سعرية، ويصل من أقرب نقطة إليك.',
				'▪  الرياض: المستودع الرئيسي وخدمة المنطقة الوسطى والشرقية.',
				'▪  جدة: مستودع المنطقة الغربية والجنوبية.',
				'▪  توريد مجدول للموزعين وأصحاب الأساطيل في كل مناطق المملكة.',
				'آراء عملائنا',
				'كنت أطلب من ثلاثة موردين عشان أكمّل المقاسات. الحين طلبية واحدة وتخلص القصة، والبضاعة تطلع من مستودع الرياض في يومين.',
				'صاحب محل إطارات — الرياض',
				'اللي فرق معنا إن التوريد صار مجدول. الإطارات توصل قبل ما تنتهي عندنا، فما وقفت لنا شاحنة انتظاراً لإطار من سنة تقريباً.',
				'مدير أسطول، شركة نقل بري — الدمام',
				'سألتهم عن مقاس معيّن للحافلات، رجعوا لي بترشيحين وفرق السعر وسبب كل واحد. أول مورّد يشرح لي قبل ما يبيع.',
				'مسؤول مشتريات، شركة نقل عاملين — جدة',
				'الأسئلة الشائعة',
				'تبيعون للأفراد أم للتجار فقط؟',
				'نشاطنا الأساسي جملة وتوزيع. نخدم التجار والموزعين وأصحاب الأساطيل، ونوجّه الأفراد إلى أقرب نقطة بيع تحمل منتجاتنا.',
				'كم مدة التوريد؟',
				'ما هو متوفر في مستودعات الرياض وجدة يخرج خلال أيام. الطلبات الخاصة تُحدَّد مدتها في عرض السعر.',
				'من أين تستوردون؟',
				'من مصانع معتمدة في الصين وكوريا الجنوبية وتايلند. نختار المصنع بناءً على سجلّه لا على أرخص عرض.',
				'كيف أعرف المقاس المناسب لسيارتي؟',
				'استخدم أداة اختيار الإطار في الموقع، أو أرسل لنا الأرقام المكتوبة على جانب إطارك الحالي.',
				'الدعوة الختامية',
				'أرسل مقاساتك، وخلّ الباقي علينا',
				'عرض سعر خلال يوم عمل واحد، بدون التزام، وبدون أن تشرح نفسك مرتين. ما عندك المقاسات؟ أرسل صورة لجانب الإطار وكفى.',
				'اطلب عرض سعر   ·   تواصل واتساب',
				'الفوتر',
				'الشركة: عن الشركة · اعتمادات الشركة · الوكالات · من نخدم · للتجار والأساطيل',
				'الإطارات: إطارات الركاب · الدفع الرباعي · الشاحنات والحافلات · اختر إطارك · دليل الإطارات',
				'تواصل: 2040 446 11 966+ · واتساب 3138 431 50 966+ · info@binshihontrd.com',
				'8034 طريق علي بن أبي طالب، حي الخالدية، الرياض 12874 - 4625، المملكة العربية السعودية',
				'فيسبوك · إكس · إنستقرام · تيك توك',
				'جميع الحقوق محفوظة — شركة عبدالرب قاسم بن شيهون للإطارات'
			)
		),
		'en' => array(
			'title' => 'Home',
			'blocks' => array(
				'Navigation',
				'Home   ·   Company   ·   Tires   ·   Find Your Tire   ·   Brands   ·   Certifications   ·   Contact',
				'Request a Quote',
				'Hero',
				'Trusted every mile',
				'Your tires arrive before you need them, at importer pricing',
				'We import from approved factories in China, South Korea and Thailand, and we hold the stock in Riyadh and Jeddah. So when you order, the goods are already on the ground rather than somewhere at sea, and the price reaches you from the source with nobody in between.',
				'Get a quote within one business day',
				'Browse Tires',
				'Trust strip',
				'An accredited operator, not just a supplier',
				'▪  Authorized Economic Operator (Priority), granted by ZATCA in September 2025',
				'▪  Serving the Saudi market since 2016',
				'▪  Eleven international brands under one roof',
				'▪  Two main warehouses, in Riyadh and Jeddah',
				'Brands we carry: Nexen · Trazano · Boto · Joyall · Onyx · Landspider · Cachland · Anniet · Fiermax · Kaytoon · ZC',
				'Tire finder',
				'Which tire is right for your vehicle?',
				'Answer a few quick questions and we will come back with the size and a recommendation based on how you actually drive, not on price alone. Under a minute, and no sign-up.',
				'Start now',
				'Key features',
				'Direct import',
				'We buy from the factory, not from a middleman. The price that reaches you has passed through as few hands as possible, and any quality issue goes straight back to the plant.',
				'Stock on the ground',
				'The warehouses are full before you order. Your size is here today, not on a container still in transit.',
				'Sizes that cover the market',
				'From the family sedan to the heavy hauler. Common sizes are always in stock, and hard-to-find ones we bring in to order.',
				'The solution',
				'Choose by how you drive, not by price alone.',
				'Passenger tires',
				'Sedans, hatchbacks and everyday driving in town and on the highway. Stable at speed, braking you can rely on, and a quiet cabin.',
				'SUV and mixed terrain',
				'Asphalt and dirt on the same trip. A reinforced sidewall and a tread that grips sand and gravel without turning noisy on the paved road.',
				'Truck and bus',
				'Heavy loads over long intercity runs, with patterns specified for steer, drive and trailer positions.',
				'The Velocità Collection',
				'Made for every road you take. A tread that clears water, a compound that takes the heat, and a working life you can plan around.',
				'View sizes',
				'The numbers',
				'▪  2016 — the year we started',
				'▪  11 — international brands',
				'▪  3 — sourcing markets',
				'▪  2 — main warehouses',
				'Benefits',
				'Lower cost per kilometre',
				'The number that matters is not the price on the tire, it is how far it ran before replacement. We help you choose on that basis.',
				'Supply that shows up',
				'Customs accreditation means faster clearance, and local stock means your order is not waiting on a shipment.',
				'The right pick, first time',
				'Send us the size or the vehicle model, and our team comes back with a recommendation based on how you actually use it.',
				'Pricing you can trace',
				'We are the importer. There is no extra layer adding to the price and then explaining why.',
				'How it works',
				'▪  Send us the sizes and quantities, or just your vehicle model.',
				'▪  You get a clear quote and a firm delivery window.',
				'▪  We prepare the order from the Riyadh or Jeddah warehouse.',
				'▪  It arrives at your site, and you stay with the same point of contact.',
				'Start now',
				'Our network and brands',
				'Eleven international brands work with us, held across two warehouses in Riyadh and Jeddah, with a distribution network reaching the regions of the Kingdom. One order covers several brands and several price tiers, and it ships from the point closest to you.',
				'▪  Riyadh: the main warehouse, serving the Central and Eastern regions.',
				'▪  Jeddah: the warehouse for the Western and Southern regions.',
				'▪  Scheduled supply for distributors and fleet owners across the Kingdom.',
				'What our customers say',
				'I used to order from three suppliers just to complete a size list. Now one order covers it, and the goods leave the Riyadh warehouse within two days.',
				'Tire shop owner — Riyadh',
				'What changed for us was the scheduling. The tires arrive before we run out, and we have not had a truck standing idle waiting on one for about a year.',
				'Fleet manager, road haulage company — Dammam',
				'I asked about a specific bus size and they came back with two options, the price difference, and the reason for each. First supplier who explained before selling.',
				'Procurement officer, staff transport company — Jeddah',
				'Frequently asked questions',
				'Do you sell to individuals or only to traders?',
				'Our core business is wholesale and distribution. We serve traders, distributors and fleet owners, and we point individual buyers to the nearest outlet carrying our products.',
				'How long does supply take?',
				'Anything held in the Riyadh or Jeddah warehouses ships within days. Special orders carry a stated lead time in the quote.',
				'Where do you import from?',
				'From approved factories in China, South Korea and Thailand. We chose the plant on its record, not on the lowest offer.',
				'How do I find the right size for my car?',
				'Use the tire finder on the site or send us the numbers printed on the sidewall of your current tire.',
				'Closing call',
				'Send us your sizes and leave the rest with us',
				'A quote within one business day, no commitment, and no need to explain yourself twice. No sizes to hand? A photo of the sidewalk is enough.',
				'Request a Quote   ·   Chat on WhatsApp',
				'Footer',
				'Company: About · Certifications · Brands · Who we serve · Trade and fleet',
				'Tires: Passenger · SUV · Truck and bus · Find your tire · Tire guide',
				'Contact: +966 11 446 2040 · WhatsApp +966 50 431 3138 · info@binshihontrd.com',
				'8034 Ali Bin Abi Talib Road, Al Khalidiyyah, Riyadh 12874-4625, Saudi Arabia',
				'Facebook · X · Instagram · TikTok',
				'All rights reserved — Abdulrab Qasem Bin Shihoun Tires Company'
			)
		)
	),
	'tire-finder' => array(
		'slug' => 'tire-finder',
		'number' => '02',
		'ar' => array(
			'title' => 'أداة اختيار الإطار',
			'blocks' => array(
				'شاشة البداية',
				'ما هو الإطار المناسب لسيارتك؟',
				'جاوب على أسئلة سريعة، ونرجع لك بالمقاس وبترشيح مبني على استخدامك الفعلي لا على السعر وحده. أقل من دقيقة، وبدون تسجيل.',
				'▪  سبعة أسئلة، كل واحد بضغطة.',
				'▪  ما نطلب منك اسم ولا بريد قبل النتيجة.',
				'▪  الترشيح من المتوفر فعلاً في مستودعاتنا.',
				'ابدأ  ←',
				'الأسئلة',
				'السؤال 1 — نوع مركبتك',
				'وش نوع المركبة اللي تدوّر لها إطارات؟',
				'○  سيارة ركاب (سيدان أو هاتشباك)',
				'○  دفع رباعي أو SUV',
				'○  فان أو نقل خفيف',
				'○  شاحنة أو مقطورة',
				'○  حافلة',
				'السؤال 2 — الطريق',
				'وين تمشي أغلب الوقت؟',
				'○  داخل المدينة',
				'○  خطوط سريعة بين المدن',
				'○  طرق ترابية وبر',
				'○  خليط بين هذا وذاك',
				'السؤال 3 — المسافة',
				'كم تمشي في الشهر تقريباً؟',
				'○  أقل من 1,000 كم',
				'○  من 1,000 إلى 3,000 كم',
				'○  من 3,000 إلى 6,000 كم',
				'○  أكثر من 6,000 كم',
				'السؤال 4 — الأولوية',
				'وش أهم شي عندك في الإطار؟',
				'○  عمر أطول وكيلومترات أكثر',
				'○  ثبات وفرملة على السرعة',
				'○  هدوء وراحة داخل السيارة',
				'○  أقل سعر ممكن مع جودة مقبولة',
				'السؤال 5 — الحمولة',
				'تحمّل أوزان ثقيلة أو تسحب مقطورة؟',
				'○  لا، استخدام عادي',
				'○  أحياناً',
				'○  دائماً، وهذا أساس شغلي',
				'السؤال 6 — المقاس',
				'وش مقاس إطارك الحالي؟',
				'اكتب المقاس مثل 215/60R17',
				'○  ما أعرف مقاسي',
				'إذا اختار «ما أعرف مقاسي»',
				'لا مشكلة. المقاس مكتوب على جانب الإطار نفسه، أو على ملصق داخل باب السائق. صوّره وأرسله لنا، أو اكتب لنا موديل سيارتك وسنة الصنع ونستخرجه لك.',
				'○  أرسل صورة جانب الإطار',
				'○  اكتب موديل السيارة وسنة الصنع',
				'السؤال 7 — الكمية',
				'كم إطار تحتاج؟',
				'○  من 1 إلى 4 (سيارة واحدة)',
				'○  من 5 إلى 20',
				'○  أكثر من 20 (طلب جملة)',
				'نصوص الواجهة',
				'▪  شريط التقدّم: السؤال 3 من 7',
				'▪  أزرار التنقل: التالي  ·  رجوع  ·  ابدأ من جديد',
				'▪  أثناء المعالجة: نراجع المتوفر في المستودعات…',
				'▪  عند تخطي سؤال: تقدر تتخطاه، بس النتيجة تكون أدق لو جاوبت.',
				'شاشة النتيجة',
				'هذا الترشيح المناسب لك',
				'اخترنا لك بناءً على نوع مركبتك، وطريقك، والمسافة اللي تقطعها، والأولوية اللي حددتها. الترشيح الأول هو الأنسب، والثاني بديل لو كانت الميزانية أهم عندك.',
				'▪  الترشيح الأول: اسم العلامة + سبب الترشيح',
				'▪  البديل: اسم العلامة + الفرق بينه وبين الأول',
				'▪  المقاس الذي أدخلته',
				'▪  حالة التوفر في مستودع الرياض أو جدة',
				'اطلب عرض سعر لهذا المقاس   ·   تواصل واتساب   ·   جرّب مرة ثانية',
				'نتائج الترشيح',
				'سيارة ركاب · مدينة · الأولوية سعر',
				'الترشيح: Anniet. توازن معقول بين السعر والأداء، ويكفي احتياج القيادة اليومية داخل المدينة حيث السرعات أقل والفرامل أكثر.',
				'البديل: ZC للميزانية الأضيق مع الحفاظ على المواصفة المطلوبة.',
				'سيارة ركاب · خطوط سريعة · الأولوية ثبات',
				'الترشيح: Nexen. علامة كورية بسجل طويل في إطارات الركاب، والأنسب حين تكون السرعات عالية والمسافات طويلة.',
				'البديل: Onyx بمقاسات منتشرة وسعر أقل.',
				'سيارة ركاب · كيلومترات عالية (أجرة أو تطبيقات نقل)',
				'الترشيح: Trazano. مبني على الاستخدام المكثف، والأنسب لمن يتجاوز 3,000 كم في الشهر.',
				'البديل: Nexen إذا كان الهدوء والراحة أهم من العمر التشغيلي.',
				'سيارة ركاب · الأولوية هدوء وراحة',
				'الترشيح: Onyx. نقشة هادئة على الأسفلت وتشكيلة مقاسات تغطي أغلب السيارات في السوق.',
				'البديل: Nexen لو كنت تجمع بين الهدوء والثبات على السرعة.',
				'دفع رباعي · بر وطرق ترابية',
				'الترشيح: Landspider. جدار جانبي أقوى ونقشة تمسك الرمل والحصى، وتظل معقولة على الطريق المعبّد.',
				'البديل: مجموعة Velocità إذا كنت تخلط بين البر والخطوط السريعة.',
				'دفع رباعي · أسفلت أغلب الوقت',
				'الترشيح: مجموعة Velocità. مصممة للمسافات الطويلة، بنقشة تصرّف الماء وخلطة تتحمّل حرارة الصيف.',
				'البديل: Nexen لو كان الاستخدام عائلياً داخل المدينة أكثر منه سفراً.',
				'فان أو نقل خفيف',
				'الترشيح: Cachland. مصممة لتحمّل الحمولة المتكررة والتوقف والانطلاق داخل المدن.',
				'البديل: Fiermax بمواصفة مطابقة وسعر أقل للأساطيل الصغيرة.',
				'شاحنة أو مقطورة · خطوط طويلة',
				'الترشيح: Boto. بنية تتحمّل الأحمال العالية والتشغيل المتواصل بين المدن، مع نقشات مخصصة لكل محور.',
				'البديل: Joyall لأساطيل النقل التي تبدّل بكميات كبيرة.',
				'شاحنة · توزيع داخل المدن',
				'الترشيح: Joyall. مناسبة للتوقف والانطلاق المتكرر والمناورة في الشوارع الضيقة.',
				'البديل: Cachland للنقل الخفيف والمتوسط.',
				'حافلة نقل ركاب أو عاملين',
				'الترشيح: Joyall. أداء ثابت على الخطوط المتكررة وحمولة الركاب الكاملة.',
				'البديل: Boto للحافلات التي تعمل على خطوط طويلة بين المدن.',
				'طلب جملة · أكثر من 20 إطاراً',
				'طلبك بهذا الحجم يستاهل تسعيرة خاصة. نحوّلك مباشرة إلى فريق الجملة، ويرجع لك عرض سعر بالمقاسات والكميات ومدة التوريد خلال يوم عمل.',
				'حوّلني لفريق الجملة',
				'إجابات غير كافية',
				'إجاباتك تحتمل أكثر من خيار، والفرق بينها يعتمد على تفاصيل ما سألنا عنها. أرسل لنا المقاس وطريقة استخدامك، ويرجع لك أحد فنيينا بترشيح دقيق خلال يوم عمل.',
				'خلّ فريقنا يرشّح لي'
			)
		),
		'en' => array(
			'title' => 'Tire Finder',
			'blocks' => array(
				'Opening screen',
				'Which tire is right for your vehicle?',
				'Answer a few quick questions and we will come back with the size and a recommendation based on how you actually drive, not on price alone. Under a minute, and no sign-up.',
				'▪  Seven questions, one tap each.',
				'▪  No name or email required before you see the result.',
				'▪  Recommendations come from what is actually in our warehouses.',
				'Start  →',
				'The questions',
				'Question 1 — Vehicle type',
				'What are you buying tires for?',
				'○  Passenger car (sedan or hatchback)',
				'○  SUV or 4x4',
				'○  Van or light commercial',
				'○  Truck or trailer',
				'○  Bus',
				'Question 2 — Road',
				'Where do you drive most of the time?',
				'○  In the city',
				'○  Intercity highways',
				'○  Dirt roads and desert',
				'○  A mix of all of these',
				'Question 3 — Distance',
				'Roughly how far do you drive each month?',
				'○  Under 1,000 km',
				'○  1,000 to 3,000 km',
				'○  3,000 to 6,000 km',
				'○  Over 6,000 km',
				'Question 4 — Priority',
				'What matters most to you in a tire?',
				'○  Longer life and more kilometres',
				'○  Grip and braking at speed',
				'○  A quiet, comfortable ride',
				'○  The lowest price at acceptable quality',
				'Question 5 — Load',
				'Do you carry heavy loads or tow a trailer?',
				'○  No, normal use',
				'○  Sometimes',
				'○  Always, it is the core of my work',
				'Question 6 — Size',
				'What size are your current tires?',
				'Enter it like 215/60R17',
				'○  I don’t know my size',
				'If they choose "I don’t know my size"',
				'Not a problem. The size is printed on the sidewall itself, or on a label inside the driver door. Photograph it and send it over, or give us your vehicle model and year and we will work it out for you.',
				'○  Send a photo of the sidewall',
				'○  Enter vehicle model and year',
				'Question 7 — Quantity',
				'How many tires do you need?',
				'○  1 to 4 (one vehicle)',
				'○  5 to 20',
				'○  More than 20 (wholesale)',
				'Interface copy',
				'▪  Progress bar: Question 3 of 7',
				'▪  Navigation: Next  ·  Back  ·  Start over',
				'▪  While processing: Checking what is in the warehouses…',
				'▪  On skipping a question: You can skip this, but answering makes the result more accurate.',
				'Result screen',
				'Here is your recommendation',
				'We based this on your vehicle type, the roads you drive, the distance you cover and the priority you chose. The first option is the closest fit; the second is the alternative if budget matters more.',
				'▪  First recommendation: brand name and the reason behind it',
				'▪  Alternative: brand name and how it differs from the first',
				'▪  The size you entered',
				'▪  Availability in the Riyadh or Jeddah warehouse',
				'Request a quote for this size   ·   Chat on WhatsApp   ·   Try again',
				'Recommendation results',
				'Passenger car · city · price priority',
				'Recommended: Anniet. A sensible balance of price and performance, and enough for daily city driving where speeds are lower and braking is more frequent.',
				'Alternative: ZC for a tighter budget while keeping the required specification.',
				'Passenger car · highway · grip priority',
				'Recommended: Nexen. A Korean make with a long record in passenger tires, and the better fit when speeds are high and distances long.',
				'Alternative: Onyx, with widely available sizes at a lower price.',
				'Passenger car · high mileage (taxi or ride-hailing)',
				'Recommended: Trazano. Built around heavy use, and the better choice above 3,000 km a month.',
				'Alternative: Nexen if comfort and quiet matter more than working life.',
				'Passenger car · comfort priority',
				'Recommended: Onyx. A quiet pattern on asphalt and a size range covering most cars on the road.',
				'Alternative: Nexen if you want quiet and high-speed stability together.',
				'SUV · desert and dirt roads',
				'Recommended: Landspider. A stronger sidewall and a tread that grips sand and gravel while staying reasonable on the paved road.',
				'Alternative: the Velocità Collection if you mix desert driving with highway runs.',
				'SUV · mostly asphalt',
				'Recommended: the Velocità Collection. Built for long distances, with a tread that clears water and a compound that takes summer heat.',
				'Alternative: Nexen if the use is mostly family driving in town rather than travel.',
				'Van or light commercial',
				'Recommended: Cachland. Designed for repeated loading and the stop-start rhythm of city work.',
				'Alternative: Fiermax, meeting the same specification at a lower price for smaller fleets.',
				'Truck or trailer · long haul',
				'Recommended: Boto. A casing built for heavy loads and continuous intercity running, with patterns for each axle position.',
				'Alternative: Joyall for haulage fleets replacing in volume.',
				'Truck · urban distribution',
				'Recommended: Joyall. Suited to frequent stop-start work and manoeuvring in tight streets.',
				'Alternative: Cachland for light and medium transport.',
				'Passenger or staff bus',
				'Recommended: Joyall. Steady performance on repeated routes at full passenger load.',
				'Alternative: Boto for buses running long intercity routes.',
				'Wholesale · more than 20 tires',
				'An order this size deserves its own pricing. We pass you straight to the wholesale team, and a quote covering sizes, quantities and lead time comes back within one business day.',
				'Take me to the wholesale team',
				'Not enough to go on',
				'Your answers point to more than one option, and the difference comes down to details we did not ask about. Send us the size and how you use the vehicle, and one of our technicians will come back with a precise recommendation within one business day.',
				'Let your team recommend for me'
			)
		)
	),
	'about' => array(
		'slug' => 'about',
		'number' => '03',
		'ar' => array(
			'title' => 'عن الشركة',
			'blocks' => array(
				'تسع سنوات ونحن نغذّي السوق السعودي بالإطارات، والطريقة لم تتغيّر: نشتري من المصنع، ونخزّن في المملكة، ونسلّم في وقتنا.',
				'من نحن',
				'شركة عبدالرب قاسم بن شيهون للإطارات شركة سعودية تأسست عام 2016، مقرها الرياض، وتعمل في استيراد الإطارات وتوزيعها على مستوى المملكة.',
				'بدأنا من ملاحظة بسيطة: السوق السعودي يدفع كثيراً في إطارات جيدة، والسبب ليس المصنع بل عدد الأيدي التي تمر عليها البضاعة قبل أن تصل. فذهبنا مباشرة إلى مصادر التصنيع في الصين وكوريا الجنوبية وتايلند، وبنينا علاقات طويلة مع مصانع نثق في سجلّها، وصرنا نستورد بكميات تجعل السعر في صالح عميلنا.',
				'اليوم لدينا مستودعان في الرياض وجدة، وشبكة توزيع تغطي مناطق المملكة، ومحفظة وكالات تضم إحدى عشرة علامة تخدم كل فئة: من المستخدم الذي يبحث عن التوفير، إلى شركة النقل التي لا تقبل بأداء متذبذب.',
				'كيف نعمل',
				'الاستيراد',
				'نتعامل مباشرة مع مصانع معتمدة، ونختار المصنع بناءً على سجلّه في الجودة لا على أرخص عرض يصلنا.',
				'التوزيع',
				'مستودعات في الرياض وجدة وشبكة توزيع منظّمة، حتى يصل الطلب بسرعة داخل المدينة وفي أطراف المملكة على السواء.',
				'الجودة',
				'كل إطار نوفّره مطابق للمواصفات المعتمدة، ومختار ليتحمّل حرارة الصيف السعودي والمسافات الطويلة على الخطوط السريعة.',
				'التنوّع',
				'تشكيلة تغطي السيارات الخاصة والدفع الرباعي والشاحنات والحافلات، بمقاسات وفئات أسعار مختلفة.',
				'الرؤية',
				'أن نكون الاسم الأول الذي يخطر على بال العميل السعودي حين يفكّر في الإطارات، بجودة لا نتنازل عنها، وخدمة تحفظ العميل، وتشكيلة تواكب تغيّر السوق.',
				'الرسالة',
				'نوفّر إطارات موثوقة وحلول توريد مرنة تخدم السوق المحلي، ونبني مع عملائنا وموردينا علاقة طويلة أساسها الوضوح والالتزام بالوعد.',
				'قيمنا',
				'▪  الاحترام: نتعامل مع العميل والمورّد بالأدب نفسه، سواء طلب إطاراً واحداً أو حاوية كاملة.',
				'▪  التميّز: لا نقبل بضاعة تأتي أقل من المعيار الذي وعدنا به.',
				'▪  الابتكار: نبحث دائماً عن موديلات ومقاسات جديدة يحتاجها السوق.',
				'▪  التعاون: نعمل مع شركائنا كفريق واحد، ونتبادل الخبرة دون تحفّظ.',
				'▪  المرونة: نتأقلم مع تغيّر الطلب، ونتخذ قرارات سريعة تخدم الشريك.'
			)
		),
		'en' => array(
			'title' => 'About the company',
			'blocks' => array(
				'Nine years supplying tires to the Saudi market, and the method has not changed: buy from the factory, hold the stock in the Kingdom, deliver on time.',
				'Who we are',
				'Abdulrab Qasem Bin Shihoun Tires Company is a Saudi business founded in 2016. We are based in Riyadh and we import and distribute tires across the Kingdom.',
				'We started from a simple observation. The Saudi market was paying a great deal for good tires, and the reason was not the factory but the number of hands the goods passed through on the way. So we went directly to the manufacturing sources in China, South Korea and Thailand, built long relationships with plants whose record we trust, and began importing at volumes that put the price in our customer’s favour.',
				'Today we run two warehouses, in Riyadh and Jeddah, with a distribution network covering the regions of the Kingdom, and a portfolio of eleven brands serving every segment, from the driver looking for value to the transport company that will not accept uneven performance.',
				'How we work',
				'Importing',
				'We deal directly with approved factories, and we pick the plant on its quality record rather than on the cheapest offer that lands in our inbox.',
				'Distribution',
				'Warehouses in Riyadh and Jeddah and an organised distribution network, so orders move quickly inside the city and out to the far regions alike.',
				'Quality',
				'Every tire we supply meets the approved specifications and is chosen to handle the Saudi summer and long runs on the highway.',
				'Range',
				'A selection covering passenger cars, SUVs, trucks and buses, across different sizes and price tiers.',
				'Vision',
				'To be the first name a Saudi customer thinks of when tires come up, with quality we will not compromise, service that keeps customers with us, and a range that moves with the market.',
				'Mission',
				'To supply dependable tires and flexible supply solutions to the local market, and to build long relationships with our customers and suppliers based on clarity and keeping our word.',
				'Our values',
				'▪  Respect. We treat customer and supplier with the same courtesy, whether the order is one tire or a full container.',
				'▪  Excellence. We do not accept goods that arrive below the standard we promised.',
				'▪  Innovation. We keep looking for new patterns and sizes the market needs.',
				'▪  Collaboration. We work with our partners as one team and share what we know without holding back.',
				'▪  Flexibility. We adapt to shifts in demand and make quick decisions that serve the partner.'
			)
		)
	),
	'certifications' => array(
		'slug' => 'certifications',
		'number' => '04',
		'ar' => array(
			'title' => 'اعتمادات الشركة',
			'blocks' => array(
				'اعتماد رسمي يعني إجراءات أسرع، ومخزوناً لا ينقطع، وبضاعة تصل في وقتها.',
				'المشغل الاقتصادي المعتمد (أولوية)',
				'في الثالث من سبتمبر 2025 انضمّت شركة عبدالرب قاسم بن شيهون للإطارات رسمياً إلى برنامج المشغل الاقتصادي المعتمد (أولوية)، باعتماد من هيئة الزكاة والضريبة والجمارك.',
				'البرنامج شراكة بين الهيئة والمنشآت التجارية الموثوقة، هدفها تأمين سلسلة الإمداد وتسهيل حركة التجارة. المنشأة لا تنضم إليه إلا بعد التحقق من التزامها بالمعايير الدولية، وبعدها تحصل على مزايا وتسهيلات جمركية.',
				'أهداف البرنامج',
				'▪  تعزيز الشراكة بين الجمارك والمنشآت التجارية.',
				'▪  تسهيل التجارة وسرعة انسياب البضائع.',
				'▪  رفع مستوى أمن سلسلة الإمداد العالمية.',
				'▪  دعم الامتثال للمعايير والاشتراطات الدولية.',
				'ماذا يعني هذا لك',
				'▪  إجراءات جمركية أسرع، فتخرج البضاعة من الميناء في وقت أقصر.',
				'▪  فسح أسرع، فالمخزون عندنا لا ينقطع وطلبك لا يتأخر.',
				'▪  تكاليف تشغيلية أقل، فالسعر الذي يصلك أعدل.',
				'▪  التزام موثّق بالمعايير، فما تشتريه مطابق ونظامي.',
				'هذا الاعتماد شهادة رسمية بأن طريقة عملنا مراجَعة ومعتمدة، ويعكس دور الشركة في دعم مكانة المملكة كمركز لوجستي عالمي.'
			)
		),
		'en' => array(
			'title' => 'Certifications',
			'blocks' => array(
				'Formal accreditation means faster procedures, stock that does not run dry, and goods that arrive when they should.',
				'Authorized Economic Operator (Priority)',
				'On 3 September 2025, Abdulrab Qasem Bin Shihoun Tires Company formally joined the Authorized Economic Operator (Priority) programme, accredited by the Zakat, Tax and Customs Authority.',
				'The programme is a partnership between the Authority and trusted commercial entities, set up to secure the supply chain and ease the movement of trade. A business joins only after its compliance with international standards has been verified, and it then receives a set of customs benefits and facilitations.',
				'What the programme sets out to do',
				'▪  Strengthen the partnership between customs and commercial businesses.',
				'▪  Ease trade and speed up the flow of goods.',
				'▪  Raise the security of the global supply chain.',
				'▪  Support compliance with international standards and requirements.',
				'What it means for you',
				'▪  Faster customs procedures, so goods leave the port in less time.',
				'▪  Faster clearance, so our stock holds and your order is not delayed.',
				'▪  Lower operating costs, so the price that reaches you is fairer.',
				'▪  Documented compliance, so what you buy is fully in order.',
				'The accreditation is formal confirmation that the way we operate has been reviewed and approved, and it reflects the company’s part in supporting the Kingdom’s standing as a global logistics hub.'
			)
		)
	),
	'tires' => array(
		'slug' => 'tires',
		'number' => '05',
		'ar' => array(
			'title' => 'الإطارات',
			'blocks' => array(
				'اختر حسب استخدامك، لا حسب السعر وحده. الإطار المناسب لطريقك يوفّر عليك أكثر مما يوفّره الإطار الأرخص.',
				'تشكيلتنا مقسّمة إلى ثلاثة أقسام تغطي احتياج السوق السعودي: إطارات الركاب للاستخدام اليومي، إطارات الدفع الرباعي للطرق المختلطة، وإطارات الشاحنات والحافلات للحمولات العالية والمسافات الطويلة. كل قسم فيه أكثر من علامة وأكثر من فئة سعرية.',
				'كيف نختار ما نستورده',
				'▪  المقاس مطلوب فعلاً في السوق السعودي، لا مجرد رقم في كتالوج المصنع.',
				'▪  الخلطة المطاطية تتحمّل درجات الحرارة المرتفعة صيفاً.',
				'▪  المصنع لديه سجل التزام بالمواصفات وبمواعيد الإنتاج.',
				'▪  التوفر مستمر، حتى لا يجد العميل المقاس مرة ويفقده في المرة التالية.',
				'لست متأكداً أي قسم يناسبك؟',
				'استخدم أداة اختيار الإطار. سبعة أسئلة، ونرجع لك بترشيح مبني على استخدامك الفعلي.',
				'اختر إطارك'
			)
		),
		'en' => array(
			'title' => 'Tires',
			'blocks' => array(
				'Choose by how you drive, not by price alone. The right tire for your road saves you more than the cheapest one does.',
				'Our range is split into three categories that cover what the Saudi market asks for: passenger tires for everyday driving, SUV tires for mixed terrain, and truck and bus tires for heavy loads over long distances. Each category carries more than one brand and more than one price tier.',
				'How we decide what to import',
				'▪  The size is genuinely in demand in Saudi Arabia, not just a number in a factory catalogue.',
				'▪  The rubber compound holds up to high summer temperatures.',
				'▪  The plant has a record of meeting both specification and production dates.',
				'▪  Availability is continuous, so a customer who finds a size once finds it again.',
				'Not sure which category fits?',
				'Use the tire finder. Seven questions, and we come back with a recommendation based on how you actually drive.',
				'Find your tire'
			)
		)
	),
	'passenger-tires' => array(
		'slug' => 'passenger-tires',
		'number' => '06',
		'ar' => array(
			'title' => 'إطارات الركاب',
			'blocks' => array(
				'للسيدان والهاتشباك والاستخدام اليومي داخل المدن وعلى الخطوط السريعة.',
				'اخترنا موديلات هذا القسم بحيث تعطيك ثباتاً على السرعة، وفرملة تعتمد عليها، وهدوءاً داخل السيارة، وعمراً أطول قدر ما يسمح به الاستخدام. المقاسات المتوفرة تغطي أغلب السيارات المنتشرة في السوق السعودي، من الفئة الاقتصادية إلى الفئة المتوسطة والكبيرة.',
				'ما يميّزها',
				'▪  خلطات مطاطية تتحمّل الأسفلت الحار في الصيف.',
				'▪  مقاسات تغطي أغلب السيارات المنتشرة في المملكة.',
				'▪  خيارات اقتصادية وأخرى موجّهة للأداء.',
				'▪  بضاعة جديدة مخزّنة في مستودعات مهيّأة.',
				'الأنسب لـ',
				'▪  السيارات الخاصة للاستخدام اليومي.',
				'▪  سيارات الأجرة وتطبيقات النقل التي تقطع كيلومترات عالية.',
				'▪  شركات تأجير السيارات والأساطيل الصغيرة.',
				'العلامات في هذا القسم',
				'Nexen · Onyx · Trazano · Anniet · Fiermax · Kaytoon · ZC',
				'اطلب عرض سعر'
			)
		),
		'en' => array(
			'title' => 'Passenger tires',
			'blocks' => array(
				'For sedans, hatchbacks and daily driving in the city and on the highway.',
				'We picked the models in this category to give you stability at speed, braking you can rely on, a quiet cabin, and as much life as the usage allows. The sizes we hold cover most of the cars on Saudi roads, from the economy segment through to mid-size and large.',
				'What sets them apart',
				'▪  Rubber compounds that handle hot asphalt through the summer.',
				'▪  Sizes covering most of the cars on Saudi roads.',
				'▪  Value options alongside performance-oriented ones.',
				'▪  New stock held in properly conditioned warehouses.',
				'Best suited to',
				'▪  Private cars in daily use.',
				'▪  Taxis and ride-hailing vehicles covering high mileage.',
				'▪  Rental companies and smaller fleets.',
				'Brands in this category',
				'Nexen · Onyx · Trazano · Anniet · Fiermax · Kaytoon · ZC',
				'Request a quote'
			)
		)
	),
	'suv-tires' => array(
		'slug' => 'suv-tires',
		'number' => '07',
		'ar' => array(
			'title' => 'إطارات الدفع الرباعي والطرق المختلطة',
			'blocks' => array(
				'أسفلت وطريق ترابي في الرحلة نفسها.',
				'هذه المجموعة مصمّمة لمن يخرج من المدينة ويعود. جدارها الجانبي أقوى في مواجهة الصخر والحواف الحادة، ونقشتها تمسك الرمل والحصى دون أن تفقد هدوءها على الطريق المعبّد. وهذا التوازن هو ما يفرق بين إطار يخدمك في الرحلتين وإطار يجبرك على الاختيار بينهما.',
				'ما يميّزها',
				'▪  جدار جانبي مقوّى يتحمّل الاحتكاك والخدوش.',
				'▪  نقشة متوازنة بين الأسفلت والطرق غير المعبّدة.',
				'▪  قدرة تحمّل أعلى للحرارة في الرحلات الطويلة.',
				'▪  مقاسات تناسب سيارات الدفع الرباعي المنتشرة في المملكة.',
				'الأنسب لـ',
				'▪  رحلات نهاية الأسبوع والتخييم.',
				'▪  العمل الميداني في المواقع والطرق غير المعبّدة.',
				'▪  السفر الطويل بين المدن مع خروج متكرر عن الأسفلت.',
				'العلامات في هذا القسم',
				'Landspider · مجموعة Velocità · Nexen · Onyx',
				'اطلب عرض سعر'
			)
		),
		'en' => array(
			'title' => 'SUV and mixed terrain tires',
			'blocks' => array(
				'Asphalt and dirt on the same trip.',
				'This group is built for drivers who leave the city and come back. The sidewall is stronger against rock and sharp edges, and the tread grips sand and gravel without turning noisy on the paved road. That balance is what separates a tire that serves both trips from one that makes you choose between them.',
				'What sets them apart',
				'▪  Reinforced sidewalls that take abrasion and scuffing.',
				'▪  A tread balanced between asphalt and unpaved surfaces.',
				'▪  Higher heat tolerance on long runs.',
				'▪  Sizes matched to the SUVs common in the Kingdom.',
				'Best suited to',
				'▪  Weekend trips and camping.',
				'▪  Site work on unpaved roads.',
				'▪  Long intercity travel with frequent time off the asphalt.',
				'Brands in this category',
				'Landspider · Velocità Collection · Nexen · Onyx',
				'Request a quote'
			)
		)
	),
	'truck-bus-tires' => array(
		'slug' => 'truck-bus-tires',
		'number' => '08',
		'ar' => array(
			'title' => 'إطارات الشاحنات والحافلات',
			'blocks' => array(
				'في النقل، وقوف إطار واحد يعني تأخير شحنة وخسارة يوم عمل.',
				'لذلك اخترنا إطارات ببنية قوية وجدران جانبية متينة، تتحمّل الحمولات العالية والمسافات الطويلة بين مدن المملكة، وتعطيك كيلومترات أكثر قبل التبديل. ولأن كل محور يعمل بطريقة مختلفة، نوفّر نقشات مخصصة للمحور الأمامي والمحور القائد والمقطورة بدل استخدام إطار واحد في كل المواضع.',
				'ما يميّزها',
				'▪  بنية تقاوم الأحمال العالية والتشغيل المتواصل.',
				'▪  أداء ثابت على المسافات الطويلة في جو المملكة.',
				'▪  نقشات مخصصة للمحور الأمامي والمحور القائد والمقطورة.',
				'▪  توفّر بالكميات يخدم الأساطيل والموزعين.',
				'الأنسب لـ',
				'▪  شركات النقل البري ونقل البضائع بين المدن.',
				'▪  حافلات نقل الركاب والعاملين.',
				'▪  قطاع المقاولات والشاحنات القلابة.',
				'▪  الموزعين ومحلات الإطارات التي تخدم قطاع النقل.',
				'العلامات في هذا القسم',
				'Boto · Joyall · Cachland · Fiermax',
				'اطلب عرض سعر للأسطول'
			)
		),
		'en' => array(
			'title' => 'Truck and bus tires',
			'blocks' => array(
				'In transport, one tire down means a late shipment and a lost working day.',
				'So we chose tires with a strong casing and durable sidewalls, built to carry heavy loads over the long runs between Saudi cities and to give you more kilometres before replacement. And because each axle works differently, we supply patterns specified for steer, drive and trailer positions rather than one tire used everywhere.',
				'What sets them apart',
				'▪  A casing that stands up to heavy loads and continuous operation.',
				'▪  Steady performance over long distances in Saudi conditions.',
				'▪  Patterns specified for steer, drive and trailer positions.',
				'▪  Volume availability for fleets and distributors.',
				'Best suited to',
				'▪  Road haulage and intercity freight companies.',
				'▪  Passenger and staff transport buses.',
				'▪  Contracting work and tipper trucks.',
				'▪  Distributors and tire shops serving the transport sector.',
				'Brands in this category',
				'Boto · Joyall · Cachland · Fiermax',
				'Request a fleet quote'
			)
		)
	),
	'brands' => array(
		'slug' => 'brands',
		'number' => '09',
		'ar' => array(
			'title' => 'الوكالات',
			'blocks' => array(
				'إحدى عشرة علامة عالمية تحت سقف واحد، كل واحدة منها اختيرت لأنها تسدّ فراغاً حقيقياً في السوق.',
				'نمثّل في المملكة مجموعة علامات مختارة، ولكل واحدة منها مكانها وفئة العملاء التي تخدمها. اختيارنا لأي علامة يمر على معيارين: جودة تصنيع نثق بها، وتوفّر مستمر يضمن أن العميل يجد مقاسه حين يحتاجه.',
				'Nexen',
				'علامة كورية بحضور طويل في إطارات الركاب.',
				'الأقسام: ركاب · دفع رباعي',
				'Trazano',
				'اسم عالمي منتشر في أسواق المنطقة.',
				'الأقسام: ركاب · تجاري',
				'Boto',
				'خيار معروف في قطاع الاستخدام الثقيل.',
				'الأقسام: شاحنات · حافلات',
				'Joyall',
				'تركيز على إطارات النقل التجاري.',
				'الأقسام: شاحنات · حافلات',
				'Onyx',
				'تشكيلة ركاب بالمقاسات التي يطلبها السوق فعلاً.',
				'الأقسام: ركاب',
				'Landspider',
				'للطرق المختلطة وسيارات الدفع الرباعي.',
				'الأقسام: دفع رباعي',
				'Cachland',
				'إطارات نقل خفيف وثقيل.',
				'الأقسام: نقل خفيف · شاحنات',
				'Anniet',
				'توازن بين الأداء والسعر للاستخدام اليومي.',
				'الأقسام: ركاب',
				'Fiermax',
				'خيارات عملية بمواصفات مطابقة.',
				'الأقسام: ركاب · تجاري',
				'Kaytoon',
				'تشكيلة موجّهة لاحتياج السوق المحلي.',
				'الأقسام: ركاب',
				'ZC',
				'الخيار الاقتصادي ضمن المحفظة.',
				'الأقسام: ركاب'
			)
		),
		'en' => array(
			'title' => 'Brands',
			'blocks' => array(
				'Eleven international brands under one roof, each one chosen because it fills a real gap in the market.',
				'We represent a selected group of brands in the Kingdom, and each has its own place and its own set of customers. Any brand we take on has to pass two tests: manufacturing quality we trust, and steady availability so the customer finds his size when he needs it.',
				'Nexen',
				'A Korean make with a long record in passenger tires.',
				'Categories: Passenger · SUV',
				'Trazano',
				'A global name widely used across the region.',
				'Categories: Passenger · Commercial',
				'Boto',
				'A familiar choice in the heavy-duty segment.',
				'Categories: Truck · Bus',
				'Joyall',
				'Focused on commercial transport tires.',
				'Categories: Truck · Bus',
				'Onyx',
				'A passenger range in the sizes the market actually asks for.',
				'Categories: Passenger',
				'Landspider',
				'Built for mixed terrain and 4x4 use.',
				'Categories: SUV',
				'Cachland',
				'Light and heavy commercial tires.',
				'Categories: Light transport · Truck',
				'Anniet',
				'A balance of performance and price for daily driving.',
				'Categories: Passenger',
				'Fiermax',
				'Practical options that meet the required specifications.',
				'Categories: Passenger · Commercial',
				'Kaytoon',
				'A range aimed at local market demand.',
				'Categories: Passenger',
				'ZC',
				'The value option within the portfolio.',
				'Categories: Passenger'
			)
		)
	),
	'who-we-serve' => array(
		'slug' => 'who-we-serve',
		'number' => '10',
		'ar' => array(
			'title' => 'من نخدم',
			'blocks' => array(
				'كل قطاع له طريقة شراء مختلفة، ونتعامل مع كل واحد منها بما يناسبه.',
				'محلات الإطارات',
				'تشتري من المستورد مباشرة بأسعار جملة، وتغطي أكثر من علامة وفئة سعرية بطلبية واحدة بدل التعامل مع عدة موردين. ونجدول لك التوريد حتى لا تفضى رفوفك من المقاسات السريعة الحركة.',
				'الموزعون',
				'كميات أكبر وتسعيرة متدرّجة، مع دعم في اختيار المقاسات الأكثر طلباً في منطقتك، وأولوية في التخصيص عند وصول الشحنات الجديدة.',
				'شركات النقل والأساطيل',
				'حساب على أساس تكلفة الكيلومتر لا سعر الإطار، وترشيح لكل محور على حدة، وجدول توريد يمشي مع دورة التبديل عندك حتى لا تقف شاحنة انتظاراً لإطار.',
				'شركات النقل الجماعي',
				'حافلات نقل الركاب والعاملين تعمل على خطوط ثابتة يومياً، فنرشّح لها إطارات ثابتة الأداء على التكرار، ونوفّرها بكميات تكفي الأسطول دفعة واحدة.',
				'المقاولات والمشاريع',
				'مواقع العمل قاسية على الإطارات، فنركّز على المتانة ومقاومة القطع والاحتكاك، ونوفّر التوريد حسب مراحل المشروع.',
				'شركات التأجير',
				'أسطول متنوع المقاسات يحتاج مورّداً واحداً يغطيه كله. نوفّر التغطية والتسعيرة الموحدة والتوريد المنتظم على مدار السنة.',
				'الأفراد',
				'نشاطنا جملة، لكننا لا نترك السائل بلا جواب. استخدم أداة اختيار الإطار لتعرف المقاس والترشيح المناسب، وسنوجّهك إلى أقرب نقطة بيع تحمل منتجاتنا.'
			)
		),
		'en' => array(
			'title' => 'Who we serve',
			'blocks' => array(
				'Every sector buys differently, and we deal with each one on its own terms.',
				'Tire shops',
				'You buy from the importer at wholesale prices, and cover several brands and price tiers in a single order instead of running between suppliers. We also schedule your deliveries so the fast-moving sizes never run off your shelves.',
				'Distributors',
				'Larger volumes and tiered pricing, with help identifying the sizes most in demand in your region, and priority allocation when new shipments land.',
				'Haulage and fleets',
				'We work the numbers on cost per kilometre rather than the price of the tire, recommend for each axle separately, and set a supply schedule that follows your replacement cycle so no truck sits waiting.',
				'Passenger transport',
				'Staff and passenger buses run fixed routes every day, so we recommend tires that perform consistently under repetition, and supply them in quantities that cover the whole fleet at once.',
				'Contracting and projects',
				'Site conditions are hard on tires, so here we focus on durability and resistance to cuts and abrasion, and supply in step with the project schedule.',
				'Rental companies',
				'A mixed fleet needs one supplier who can cover all of it. We provide the coverage, a single price structure, and steady supply through the year.',
				'Individual drivers',
				'Our business is wholesale, but we do not leave a question unanswered. Use the tire finder to get your size and recommendation, and we will point you to the nearest outlet carrying our products.'
			)
		)
	),
	'trade-fleet' => array(
		'slug' => 'trade-fleet',
		'number' => '11',
		'ar' => array(
			'title' => 'للتجار والأساطيل',
			'blocks' => array(
				'تعامل مع المستورد مباشرة. أسعار جملة، وتوريد مجدول، ومحفظة كاملة في طلبية واحدة.',
				'إن كنت صاحب محل إطارات، أو موزّعاً، أو تدير أسطولاً، فالتعامل معنا يختصر عليك السلسلة كاملة. نحن المستورد، وهذا يعني أن البضاعة تصلك من المصدر دون طبقات وسطاء تضيف على السعر وتطيل مدة التوريد.',
				'ما تكسبه من الشراكة',
				'أسعار جملة',
				'تسعير تنافسي يتدرّج مع الكمية، ويظل ثابتاً طوال مدة الاتفاق.',
				'توريد منتظم',
				'نجدول التوريد حسب دورة التبديل عندك، فيصل الطلب قبل نفاد المخزون لا بعده.',
				'محفظة كاملة',
				'إحدى عشرة علامة ومقاسات متنوعة، فطلبية واحدة تكفي بدل التعامل مع أكثر من مورّد.',
				'دعم فني',
				'مساعدة في اختيار الموديل والنقشة المناسبة لكل استخدام ولكل محور.',
				'خدمة الأساطيل',
				'لدينا فريق مخصص للأساطيل يحسبها معك على أساس تكلفة الكيلومتر لا سعر الإطار وحده. نرشّح لك النقشة المناسبة لكل محور، ونضع جدول توريد يمشي مع دورة تبديلك، حتى لا تقف شاحنة انتظاراً لإطار.',
				'كيف تبدأ',
				'▪  كلّمنا على الرقم الموحّد أو الواتساب وعرّفنا على نشاطك.',
				'▪  أرسل قائمة المقاسات والكميات التي تحتاجها.',
				'▪  نرجع لك بعرض سعر واضح ومدة توريد محددة.',
				'▪  نتفق على جدولة التسليم، ونبدأ.',
				'اطلب عرض سعر جملة'
			)
		),
		'en' => array(
			'title' => 'Trade and fleet',
			'blocks' => array(
				'Deal with the importer directly. Wholesale pricing, scheduled supply, and the full portfolio in a single order.',
				'If you run a tire shop, work as a distributor, or manage a fleet, working with us shortens the whole chain. We are the importer, so the goods reach you from the source without layers of intermediaries adding to the price and stretching the lead time.',
				'What the partnership gives you',
				'Wholesale pricing',
				'Competitive pricing that scales with volume and holds steady for the term of the agreement.',
				'Regular supply',
				'We schedule deliveries around your replacement cycle, so stock arrives before it runs out rather than after.',
				'One portfolio',
				'Eleven brands and a wide spread of sizes, so a single order covers what would otherwise take several suppliers.',
				'Technical support',
				'Help choosing the right model and pattern for each application and each axle position.',
				'Fleet service',
				'We have a team dedicated to fleets that works the numbers with you on cost per kilometre rather than on the price of the tire alone. We recommend the right pattern for each axle and set a supply schedule that follows your replacement cycle, so no truck sits waiting on a tire.',
				'How to start',
				'▪  Call the main line or message us on WhatsApp and tell us about your operation.',
				'▪  Send through the sizes and quantities you need.',
				'▪  We come back with a clear quote and a firm lead time.',
				'▪  We agree the delivery schedule and get moving.',
				'Request a wholesale quote'
			)
		)
	),
	'tire-guide' => array(
		'slug' => 'tire-guide',
		'number' => '12',
		'ar' => array(
			'title' => 'دليل الإطارات',
			'blocks' => array(
				'معلومات مختصرة تساعدك على اختيار الإطار الصحيح والحفاظ عليه أطول.',
				'كيف تقرأ مقاس الإطار',
				'على جانب الإطار ستجد رمزاً مثل 215/60R17 96V، ويُقرأ كالتالي:',
				'▪  215 عرض الإطار بالمليمتر.',
				'▪  60 نسبة ارتفاع الجدار الجانبي إلى العرض.',
				'▪  R بنية شعاعية، وهي الشائعة اليوم.',
				'▪  17 مقاس الجنط بالإنش.',
				'▪  96 مؤشر الحمل، ويشير إلى أقصى وزن يتحمّله الإطار الواحد.',
				'▪  V رمز السرعة، ويشير إلى أقصى سرعة صُمّم لها الإطار.',
				'التزم دائماً بالمقاس ومؤشر الحمل ورمز السرعة المذكورة في دليل سيارتك أو على الملصق داخل باب السائق.',
				'رموز السرعة الشائعة',
				'الرمز | أقصى سرعة | الاستخدام المعتاد
Q | 160 كم/س | دفع رباعي وإطارات ثقيلة
S | 180 كم/س | سيارات عائلية
T | 190 كم/س | سيدان واستخدام يومي
H | 210 كم/س | الأكثر انتشاراً في سيارات الركاب
V | 240 كم/س | سيارات أداء ومتوسطة كبيرة
W | 270 كم/س | سيارات رياضية
Y | 300 كم/س | فئة الأداء العالي',
				'مؤشرات الحمل الشائعة',
				'المؤشر | أقصى حمل للإطار الواحد | 
91 | 615 كجم | 
94 | 670 كجم | 
96 | 710 كجم | 
98 | 750 كجم | 
100 | 800 كجم | 
104 | 900 كجم | 
108 | 1,000 كجم | 
110 | 1,060 كجم | ',
				'كيف تعرف عمر الإطار',
				'ابحث عن رمز DOT على جانب الإطار. آخر أربعة أرقام فيه تعطيك تاريخ الصنع: أول رقمين للأسبوع وآخر رقمين للسنة. فالرمز 2523 يعني الأسبوع الخامس والعشرين من عام 2023.',
				'في جو حار مثل جو المملكة يتقادم المطاط أسرع حتى لو بقيت النقشة عميقة، لذلك يُنصح بمراجعة حالة الإطار مع فني مختص بعد خمس سنوات من تاريخ الصنع.',
				'متى تبدّل إطاراتك',
				'▪  وصل عمق النقشة إلى الحد الأدنى النظامي وظهرت مؤشرات التآكل.',
				'▪  ظهرت تشققات أو انتفاخ أو تشوّه في الجدار الجانبي، وهذه حالة تبديل فوري.',
				'▪  التآكل غير متساوٍ، وغالباً سببه ضغط هواء خاطئ أو خلل في الترصيص أو الزوايا.',
				'▪  اهتزاز غير معتاد في المقود على السرعة، أو انحراف السيارة إلى جهة.',
				'▪  تقادم الإطار زمنياً حتى لو كانت الكيلومترات قليلة.',
				'ضغط الهواء',
				'▪  افحص الضغط مرة كل شهر على الأقل، وقبل أي سفر طويل.',
				'▪  اقس الضغط والإطار بارد، فالقياس بعد القيادة يعطي رقماً أعلى من الحقيقي.',
				'▪  اعتمد الرقم الموجود على ملصق باب السائق أو في دليل السيارة، لا الرقم المطبوع على الإطار.',
				'▪  لا تنسَ الإطار الاحتياطي.',
				'▪  نقص الضغط يزيد صرفية الوقود ويرفع حرارة الإطار، وزيادته تقلّل مساحة التلامس وتقسّي القيادة.',
				'تدوير الإطارات والترصيص',
				'الإطارات الأمامية والخلفية لا تتآكل بالمعدل نفسه، وتدويرها حسب توصية الصانع يوزّع التآكل ويطيل عمر الطقم كاملاً. أما الترصيص وضبط الزوايا فيمنعان التآكل الجانبي غير المتساوي، وهما أرخص بكثير من طقم إطارات جديد.',
				'العناية في الصيف',
				'▪  تجنّب الانطلاق بسرعة عالية والإطار حار بعد وقوف طويل تحت الشمس.',
				'▪  لا تحمّل السيارة فوق طاقتها، خصوصاً في سفر العائلة صيفاً.',
				'▪  افحص الضغط قبل السفر لا بعده، والحرارة العالية ترفع الضغط أثناء القيادة بشكل طبيعي.',
				'▪  راجع حالة الجدار الجانبي بعد الطرق الوعرة أو الاصطدام بالأرصفة.',
				'تخزين الإطارات',
				'▪  مكان بارد وجاف وبعيد عن الشمس المباشرة.',
				'▪  بعيداً عن الزيوت والمذيبات والمواد الكيميائية.',
				'▪  واقفة بشكل عمودي إن كانت بدون جنوط، ومكدّسة أفقياً إن كانت مركّبة على جنوط.',
				'▪  بعيداً عن مصادر الحرارة والمحركات الكهربائية.'
			)
		),
		'en' => array(
			'title' => 'Tire guide',
			'blocks' => array(
				'Short, practical notes to help you pick the right tire and keep it longer.',
				'How to read a tire size',
				'On the sidewall you will find a code such as 215/60R17 96V. It reads like this:',
				'▪  215 is the tire width in millimetres.',
				'▪  60 is the sidewall height as a percentage of the width.',
				'▪  R means radial construction, which is the standard today.',
				'▪  17 is the rim diameter in inches.',
				'▪  96 is the load index, the maximum weight a single tire can carry.',
				'▪  V is the speed rating, the maximum speed the tire is designed for.',
				'Always stay with the size, load index and speed rating given in your vehicle handbook or on the label inside the driver door.',
				'Common speed ratings',
				'Code | Maximum speed | Typical use
Q | 160 km/h | SUV and heavy-duty tires
S | 180 km/h | Family cars
T | 190 km/h | Sedans and daily driving
H | 210 km/h | The most common passenger rating
V | 240 km/h | Performance and larger mid-size cars
W | 270 km/h | Sports cars
Y | 300 km/h | High-performance segment',
				'Common load indexes',
				'Index | Maximum load per tire | 
91 | 615 kg | 
94 | 670 kg | 
96 | 710 kg | 
98 | 750 kg | 
100 | 800 kg | 
104 | 900 kg | 
108 | 1,000 kg | 
110 | 1,060 kg | ',
				'How to check a tire’s age',
				'Look for the DOT code on the sidewall. Its last four digits give the date of manufacture: the first two are the week, the last two the year. So 2523 means the twenty-fifth week of 2023.',
				'In heat like ours, rubber ages faster even when the tread is still deep, so it is worth having a qualified technician assess the tire once it passes five years from the date of manufacture.',
				'When to replace',
				'▪  The tread has worn to the legal minimum and the wear indicators are showing.',
				'▪  There are cracks, a bulge, or any deformation in the sidewall, which calls for immediate replacement.',
				'▪  Wear is uneven, usually a sign of wrong pressure or a balancing or alignment issue.',
				'▪  There is unusual vibration through the steering at speed, or the car pulls to one side.',
				'▪  The tire has aged out, even if the mileage is low.',
				'Tire pressure',
				'▪  Check the pressure at least once a month, and before any long trip.',
				'▪  Measure when the tires are cold, since a reading taken after driving comes out higher than the true figure.',
				'▪  Use the figure on the driver door label or in the handbook, not the number moulded into the tire.',
				'▪  Do not forget the spare.',
				'▪  Under-inflation raises fuel consumption and tire temperature, while over-inflation reduces the contact patch and hardens the ride.',
				'Rotation and alignment',
				'Front and rear tires do not wear at the same rate, and rotating them at the manufacturer’s intervals spreads the wear and extends the life of the whole set. Balancing and alignment prevent the uneven shoulder wear that ruins a tire early, and both cost far less than a new set.',
				'Summer care',
				'▪  Avoid setting off at high speed when the tires are already hot from standing in the sun.',
				'▪  Do not load the vehicle beyond its rating, particularly on family trips in summer.',
				'▪  Check pressure before a trip rather than after, since heat naturally raises it while driving.',
				'▪  Inspect the sidewall after rough roads or any kerb impact.',
				'Storage',
				'▪  Somewhere cool and dry, out of direct sunlight.',
				'▪  Away from oils, solvents and chemicals.',
				'▪  Standing upright if unmounted, stacked flat if mounted on rims.',
				'▪  Away from heat sources and electric motors.'
			)
		)
	),
	'faq' => array(
		'slug' => 'faq',
		'number' => '13',
		'ar' => array(
			'title' => 'الأسئلة الشائعة',
			'blocks' => array(
				'تبيعون للأفراد أم للتجار فقط؟',
				'نشاطنا الأساسي جملة وتوزيع. نخدم التجار والموزعين وأصحاب الأساطيل، ونوجّه الأفراد إلى أقرب نقطة بيع تحمل منتجاتنا.',
				'كم مدة التوريد؟',
				'ما هو متوفر في مستودعات الرياض وجدة يخرج خلال أيام. الطلبات الخاصة تُحدَّد مدتها في عرض السعر.',
				'من أين تستوردون؟',
				'من مصانع معتمدة في الصين وكوريا الجنوبية وتايلند. نختار المصنع بناءً على سجلّه لا على أرخص عرض.',
				'هل الإطارات جديدة؟',
				'كل ما نوفّره إطارات جديدة مستوردة مباشرة من مصانع معتمدة، وتُخزَّن في مستودعات مهيّأة للحفاظ على حالتها.',
				'ما معنى المشغل الاقتصادي المعتمد؟',
				'اعتماد من هيئة الزكاة والضريبة والجمارك للمنشآت الموثوقة، يمنحها فسحاً جمركياً أسرع. أثره عليك مخزون لا ينقطع وتوريد لا يتأخر.',
				'كيف أعرف المقاس المناسب لسيارتي؟',
				'استخدم أداة اختيار الإطار في الموقع، أو اقرأ الأرقام على جانب إطارك الحالي أو على الملصق داخل باب السائق وأرسلها لنا.',
				'هل أداة اختيار الإطار تحتاج تسجيل؟',
				'لا. سبعة أسئلة وتظهر لك النتيجة مباشرة. بياناتك نطلبها فقط إذا اخترت أن نرسل لك عرض سعر.',
				'هل أقدر أركّب مقاساً مختلفاً عن الأصلي؟',
				'يُفضّل الالتزام بالمقاس ومؤشر الحمل ورمز السرعة المذكورة في دليل السيارة. أي تغيير يحتاج مراجعة فني مختص أولاً.',
				'هل توفّرون مقاسات غير موجودة في المخزون؟',
				'نعم، بطلب مسبق. أرسل لنا المقاس والكمية ونحدد لك مدة التوريد في عرض السعر.',
				'هل يمكن الاتفاق على توريد دوري؟',
				'نعم. نجدول التوريد حسب دورة التبديل عندك، بحيث يصل الطلب قبل نفاد المخزون لا بعده.',
				'هل تخدمون خارج الرياض وجدة؟',
				'نعم. المستودعان يخدمان مناطق المملكة عبر شبكة التوزيع، ونحدد لك أقرب نقطة توريد ومدة التسليم عند الطلب.',
				'كيف أطلب عرض سعر؟',
				'اتصل على الرقم الموحّد، أو راسلنا على الواتساب، أو أرسل لنا قائمة المقاسات والكميات على البريد الإلكتروني، ويرجع لك الفريق خلال يوم عمل.'
			)
		),
		'en' => array(
			'title' => 'Frequently asked questions',
			'blocks' => array(
				'Do you sell to individuals or only to traders?',
				'Our core business is wholesale and distribution. We serve traders, distributors and fleet owners, and we point individual buyers to the nearest outlet carrying our products.',
				'How long does supply take?',
				'Anything held in the Riyadh or Jeddah warehouses ships within days. Special orders carry a stated lead time in the quote.',
				'Where do you import from?',
				'From approved factories in China, South Korea and Thailand. We choose the plant on its record, not on the lowest offer.',
				'Are the tires new?',
				'Everything we supply is new stock, imported directly from approved factories and held in warehouses conditioned to keep it that way.',
				'What is an Authorized Economic Operator?',
				'It is a ZATCA accreditation for trusted businesses that grants faster customs clearance. For you it means stock that holds and supply that arrives on schedule.',
				'How do I find the right size for my car?',
				'Use the tire finder on the site, or read the numbers on the sidewall of your current tire or the label inside the driver door and send them to us.',
				'Does the tire finder require sign-up?',
				'No. Seven questions and the result appears straight away. We only ask for your details if you choose to receive a quote.',
				'Can I fit a different size from the original?',
				'Staying with the size, load index and speed rating in your vehicle handbook is the safe route. Any change should be reviewed with a qualified technician first.',
				'Do you supply sizes that are not in stock?',
				'Yes, to order. Send us the size and quantity and we will state the lead time in the quote.',
				'Can we arrange recurring supply?',
				'Yes. We schedule deliveries around your replacement cycle so stock arrives before it runs out rather than after.',
				'Do you serve outside Riyadh and Jeddah?',
				'Yes. The two warehouses serve the regions of the Kingdom through our distribution network, and we confirm the nearest supply point and delivery time when you order.',
				'How do I request a quote?',
				'Call the main line, message us on WhatsApp, or email the sizes and quantities you need. The team comes back within one business day.'
			)
		)
	),
	'contact' => array(
		'slug' => 'contact',
		'number' => '14',
		'ar' => array(
			'title' => 'تواصل معنا',
			'blocks' => array(
				'عرض سعر خلال يوم عمل واحد. اختر الطريقة التي تريحك.',
				'بيانات التواصل',
				'▪  الهاتف الموحّد: 2040 446 11 966+',
				'▪  واتساب: 3138 431 50 966+',
				'▪  البريد الإلكتروني: info@binshihontrd.com',
				'▪  المقر الرئيسي: 8034 طريق علي بن أبي طالب، حي الخالدية، الرياض 12874 - 4625، المملكة العربية السعودية',
				'▪  مستودعات الرياض ومستودعات جدة على الخريطة.',
				'أوقات العمل',
				'من الأحد إلى الخميس، خلال ساعات العمل الرسمية. الرسائل التي تصل خارج الدوام يُرد عليها في أول يوم عمل.',
				'نموذج الطلب',
				'▪  الاسم',
				'▪  رقم الجوال',
				'▪  البريد الإلكتروني',
				'▪  نوع الطلب: إطارات ركاب / دفع رباعي / شاحنات وحافلات / طلب جملة / استفسار عام',
				'▪  المقاسات والكميات المطلوبة',
				'أرسل الطلب',
				'وصلتنا رسالتك، وسيرجع لك الفريق خلال يوم عمل. شكراً لثقتك.'
			)
		),
		'en' => array(
			'title' => 'Contact us',
			'blocks' => array(
				'A quote within one business day. Pick whichever channel suits you.',
				'Contact details',
				'▪  Main line: +966 11 446 2040',
				'▪  WhatsApp: +966 50 431 3138',
				'▪  Email: info@binshihontrd.com',
				'▪  Head office: 8034 Ali Bin Abi Talib Road, Al Khalidiyyah, Riyadh 12874-4625, Saudi Arabia',
				'▪  Riyadh and Jeddah warehouses on the map.',
				'Working hours',
				'Sunday to Thursday, during official business hours. Messages that arrive outside those hours are answered on the next working day.',
				'Enquiry form',
				'▪  Name',
				'▪  Mobile number',
				'▪  Email address',
				'▪  Type of enquiry: passenger / SUV / truck and bus / wholesale / general',
				'▪  Sizes and quantities required',
				'Send enquiry',
				'Your message has reached us and the team will be back to you within one business day. Thank you for your trust.'
			)
		)
	),
	'footer' => array(
		'slug' => 'footer',
		'number' => '15',
		'ar' => array(
			'title' => 'الفوتر',
			'blocks' => array(
				'الشركة',
				'عن الشركة · اعتمادات الشركة · الوكالات · من نخدم · للتجار والأساطيل',
				'الإطارات',
				'إطارات الركاب · الدفع الرباعي · الشاحنات والحافلات · اختر إطارك · دليل الإطارات',
				'تواصل',
				'الرقم الموحّد 2040 446 11 966+ · واتساب 3138 431 50 966+ · info@binshihontrd.com',
				'8034 طريق علي بن أبي طالب، حي الخالدية، الرياض 12874 - 4625، المملكة العربية السعودية',
				'تابعنا',
				'فيسبوك · إكس · إنستقرام · تيك توك',
				'حقوق النشر',
				'جميع الحقوق محفوظة — شركة عبدالرب قاسم بن شيهون للإطارات'
			)
		),
		'en' => array(
			'title' => 'Footer',
			'blocks' => array(
				'Company',
				'About · Certifications · Brands · Who we serve · Trade and fleet',
				'Tires',
				'Passenger · SUV · Truck and bus · Find your tire · Tire guide',
				'Contact',
				'Main line +966 11 446 2040 · WhatsApp +966 50 431 3138 · info@binshihontrd.com',
				'8034 Ali Bin Abi Talib Road, Al Khalidiyyah, Riyadh 12874-4625, Saudi Arabia',
				'Follow us',
				'Facebook · X · Instagram · TikTok',
				'Copyright',
				'All rights reserved — Abdulrab Qasem Bin Shihoun Tires Company'
			)
		)
	)
);
